default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: pg
  password: pg

development:
  <<: *default
  database: gamer_development


test:
  <<: *default
  database: gamer_test

production:
  <<: *default
  database: <%= ENV['GAMER_DATABASE_NAME'] %>
  username: <%= ENV['GAMER_DATABASE_USERNAME'] %>
  password: <%= ENV['GAMER_DATABASE_PASSWORD'] %>
